# This workflow will build a Java project with Maven
# For more information see: https://help.github.com/actions/language-and-framework-guides/building-and-testing-java-with-maven

name: AUTO_Stock1

on:
  push:
    branches: main
  #schedule:
   # - cron: '*/15 * * * *'
   # - cron: '0/5 * * * *
    # cron表达式，10 * * * *
    # cron表达式:0/10 1,2,3,4,5,6,7 * * 1,2,3,4,5  :逢星期一、二、三、四、五、四、六及七小时，每隔10分钟播放一次
    # cron表达式，Actions时区是UTC时间，所以上午9点要往前推8个小时


jobs:
  start:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Set up JDK 1.8
        uses: actions/setup-java@v1
        with:
          java-version: 1.8
      - name: Cache local Maven repository
        uses: actions/cache@v2
        with:
          path: ~/.m2/repository
          key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
          restore-keys: |
            ${{ runner.os }}-maven-
      - name: Build with Maven
        env:
          PUSHADDTOKEN: ${{ secrets.PUSHADDTOKEN }}
          SERVICETOKEN: ${{ secrets.SERVICETOKEN }}
          WXPUSHERTOKEN: ${{ secrets.WXPUSHERTOKEN }}
          OPENAIKEYS: ${{ secrets.OPENAIKEYS }}
          TZ: Asia/Shanghai
          # 时区配置为Asia/Shanghai
        run:
          mvn compile exec:java -Dexec.mainClass="com.lxf.stock.StockMain" -Dexec.args="${SERVICETOKEN} ${PUSHADDTOKEN} ${WXPUSHERTOKEN} ${OPENAIKEYS}"
